
CREATE TABLE Points(
	pID			INT		IDENTITY(1,1) PRIMARY KEY,
	pName		TEXT	NOT NULL,
	details		TEXT	NOT NULL,
	pRank		INT		,
	picture		IMAGE	,
);

CREATE TABLE Questions (
	qID			INT		IDENTITY(1,1) PRIMARY KEY ,
	question	TEXT	NOT NULL,
);

CREATE TABLE Users (
	uName		INT			IDENTITY(1,1)	PRIMARY KEY ,
	pass		TEXT		NOT NULL,
	fName		TEXT		NOT NULL,
	lName		TEXT		NOT NULL,
	city		TEXT		NOT NULL,
	country		TEXT		NOT NULL,
	email		TEXT		NOT NULL,
	question	INT			FOREIGN KEY REFERENCES Questions(qID) ON UPDATE CASCADE ON DELETE CASCADE,
	answer		TEXT		NOT NULL,
);


CREATE TABLE Users_Points (
	uName		INT		FOREIGN KEY REFERENCES Users(uName)		ON UPDATE CASCADE ON DELETE CASCADE,
	pID			INT		FOREIGN KEY REFERENCES Points(pID)		ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY(uName, pID)
);

CREATE TABLE Categories (
	cID			INT		IDENTITY(1,1)	PRIMARY KEY ,
	cName		TEXT	NOT NULL,
);


CREATE TABLE Categories_Points (
	cID			INT		FOREIGN KEY REFERENCES Categories(cID)	ON UPDATE CASCADE ON DELETE CASCADE,
	pID			INT		FOREIGN KEY REFERENCES Points(pID)		ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY(cID, pID)
);

CREATE TABLE Reviews (
	uName		INT		FOREIGN KEY REFERENCES Users(uName)		ON UPDATE CASCADE ON DELETE CASCADE,
	pID			INT		FOREIGN KEY REFERENCES Points(pID)		ON UPDATE CASCADE ON DELETE CASCADE,
	content		TEXT	,
	score		INT		NOT NULL,
	CONSTRAINT SCORE_CON check (score between 1 and 5),
	PRIMARY KEY(uName, pID)

);




