SET IDENTITY_INSERT Points ON
Insert into Points
(pID,pName,cID,picture,details)
VALUES
(10,'Park Guell',1,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Parks/Park-Guell.jpg?raw=true','The Park Guell is the most iconic park in Barcelona, designed by the architect Antoni Gaudi, and known all over the world because of its breakthrough ceramics, which decorate all of its surroundings: the banks, temples, statues… It has a lovely atmosphere that will sure enchant you while you just simply take a breath and relax above the city.'),
(11,'Parc del laberint',1,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Parks/laberint-horta.jpg?raw=true','In this park, also known as the Hortas Labyrinth, you will be able to relax for a while and enjoy the quiet on it, since it is not full of tourists because of its location (it is not in the city centre). The name of this park (Parc del Laberint= Labyrinth Park) perfectly describes its purpose: it has a big maze in it dedicated to Theseus and Ariadne, from the Greek mythology, whose myth told that Theseus used a ball of thread to find his way out of the labyrinth and save Ariadne, who was captured by the minotaur. You can find other mythological elements all over the park that will make you fall in love with it.'),
(12,'Parc de la Ciutadella',1,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Parks/parc-ciutadella-barcelona.jpg?raw=true','The Parc de la Ciutadella is Barcelonas oldest park, and a very good place to take long walks and relax for a while. In this park there are several attractions that may attract your attention: the Modern Art Museum; the Catalan Parliament; the Zoo, the Geologic Museum… In summer, they organize a lot of activities and events, as well as local artists concerts. It also has a beautiful lake where you can take a ride on a rowboat while you enjoy your relax surrounded by birds, ducks and swans.'),
(13,'Jardins de Joan Maragall and Palauet Albeni',1,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Parks/palauet-albeni.jpg?raw=true','The Joan Maragall gardens are one of the most beautiful green places in Barcelona, located in the Sants-Montjuic district. These elegant gardens seem to be from a fairytale, with many vegetation and high trees, outdoor sculptures and fountains, a farewell with a grassy area, and a gorgeous palace built in 1929 (Palauet Albeniz) to host the royal family, who are still going there when they visit Barcelona.'),
(14,'Montjuic Hill',1,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Parks/montjuic.jpg?raw=true','The Joan Maragall gardens are one of the most beautiful green places in Barcelona, located in the Sants-Montjuic district. These elegant gardens seem to be from a fairytale, with many vegetation and high trees, outdoor sculptures and fountains, a farewell with a grassy area, and a gorgeous palace built in 1929 (Palauet Albeniz) to host the royal family, who are still going there when they visit Barcelona.'),

(15,'Fundacio Joan Miro',2,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Museums/joan-miro.jpg?raw=true','And finally and as mentioned in a previous post Montjuic mountain could be considered the biggest park and the lung of Barcelona. It deserves for sure half a day visit, you will like it and will find a peaceful time and great views of Barcelona!'),
(16,'Museu Picasso',2,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Museums/picasso.jpg?raw=true','One of the most visited museums of Barcelona can be found in the Montjuic Mountain. The house of Joan Miro, vanguardist painter, and its work reside in a precious white building that stands out between the vegetation of the mountain. Located just in front of the Greek theater, you cannot miss the entrace, as an orange sculpture of the famous artist welcomes you.'),
(17,'National Museum of Art of Catalonia',2,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Museums/museu-d-historia-de-catalunya-cataluna.jpg?raw=true','One of the most famous Spanish painters of all time, Pablo Picasso, has his museum located in the heart of the Gothic Quarter. While walking through narrow streets full of history, you will walk past Picasso museum, where you will be able to see 4,251 works that make up the permanent collection. Furthermore, the Picasso museum, opened in 1963, also reveals his deep relationship with Barcelona: an intimate, solid relationship that was shaped in his adolescence and youth, and continued until his death..'),
(18,'FC Barcelona Museum',2,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Museums/camp-nou-experience-museum.jpg?raw=true','Enjoy the history of probably, the best football club on Earth. Being the most visited museum in Barcelona and constantly adding new items (from Maradona’s boots up to the 6 trophies Barcelona won in 2010), you are up to football history. It also includes a tour through the stadium where you will be able to see the Camp Nou stadium at its best. This tour, however, is not available on match days.'),
(19,'Museu Historia de Catalunya',2,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Museums/museu-d-historia-de-catalunya-cataluna.jpg?raw=true','Come to this museum to know more about the history of Catalonia and how its culture has survived during the centuries. Located in what it used to be the Sea House of Barcelona, you will find just outside different restaurants that will cook you fish, seafood and all kinds of foods related with sea products (such as paella restaurants, for example).'),

(20,'Sant Sebastia & Sant Miquel',3,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Beaches/sant-sebastia-sant-miquel.jpg?raw=true','This beach is full of small boats of people who go fishing or just sailing. Although it may seem unappealing, it is also unappealing for the rest of people, which makes it one of the beaches with fewer slots to suntan!'),
(21,'Barceloneta Beach',3,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Beaches/barceloneta.jpg?raw=true','Barcelonas most known beach, and the most crowded one offers you plenty of close-by small bars with terraces (chiringuitos) where you will be able to enjoy from a Mojito to Spanish food & tapas!'),
(22,'Somorrostro Beach',3,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Beaches/de-somorrostro-paseo-nova-icaria.jpg?raw=true','The Somorrostro beach has one of the finest sea wiewpoints in Barcelona. You can walk literally over the beach through its walkway!'),
(23,'Nova Icaria Beach',3,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Beaches/de-nova-icaria-volley.jpg?raw=true','Past of the sportive dock we find the Nova Icaria, a beach where you can find the nets that have become its trademark. Plenty of beach volley players around, with a young average age, make this the perfect beach for young people that want to practice beach sports!'),
(24,'Bogatell Beach',3,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Beaches/de-bogatell-volley1.jpg?raw=true','Being the beach with a highest average age of sunbathers, you can easily find the reasons. It is one of the quietest beaches in Barcelona, while being handicapped-friendly. Ramps are present; and so are public toilets for handicapped.'),

(25,'Mercat de la Boqueria',4,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Markets/boqueria.jpg?raw=true','In La Boqueria, you will be able to find traditional market shops, including mainly fruit and fish, but since the raise of immigration in Spain, everyday more shops owned by immigrants open to offer products imported from their home countries. La Boquerias trademark its his small restaurants where you will be able to eat products that cant be fresher.'),
(26,'Mercat de Santa Caterina',4,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Markets/santa-catarina.jpg?raw=true','Food-based, the market is not as exotic or spectacular as La Boqueria, but offers you a quick glimpse of the mixture between tradition and design. Being Barcelonas first covered market in 1848, and underwent massive restoration in 1997. Once the work was finished in 2005, the outcome has been impressing not only tourists, but also architects since then. Much less crowded and less tourist-oriented as La Boqueria, this market is a good opportunity to see a real-deal market in Barcelona. Also, there is a very nice restaurant inside with fresh products from the market!'),
(27,'Barceloneta',4,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Markets/barceloneta.jpg?raw=true','It is the smallest one of the ones proposed (855 square meters), but still, if you are close to the beach it is worth a visit to check out some food on the go! There are plenty of other food markets in Barcelona, as every neighbourhood has its own. Most known ones are el Mercat del Ninot, Mercat de Sant Antoni and Mercat Hostafrancs. You can check them all here! After seeing the food-based markets in Barcelona, it is now the turn of other kinds, including flea markets and art markets around town.'),
(28,'Sant Antoni Market',4,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Markets/sant-antoni.jpg?raw=true','Sunday morning, there is a flea market, known all over Barcelona for its book exchange, but also including video, DVD and magazine selling, from the 1930s to now. A must if you are a collector of antiquities! The market is currently in an alternative place, since due to the refurbishment of the old building (1882) they moved the market to a provisional place. During the works, Roman traces of an old town wer.'),
(29,'Painters market',4,'https://github.com/yonatanZax/City4U/blob/master/Points_Images/Markets/plaza-del-pi.jpg?raw=true','If you are fond of art, this is your place! The painters market is done every weekend and it reminds of Montmartre (Paris) where painters expose their works and sell their paintings to pedestrians. If you want to do so, one of the painters will make a painting of you after you negotiate the price with him or her. It is a quite beautiful and interesting street market to visit since it is in the Old part of town; you also have a very nice Gothic church right next to it.')
